```
FROM php:7.3-fpm

# Version
ENV PHPREDIS_VERSION 4.0.1
ENV SWOOLE_VERSION 4.6.6
ENV XLSWRITER_VERSION 1.3.7

# Timezone
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' > /etc/timezone
    
# 更换
RUN cd /etc/apt && cp sources.list ./sources.list.bak && rm sources.list && \
    echo "# 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释" >> sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster main contrib non-free" >> sources.list && \
    echo "# deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ buster main contrib non-free" >> sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main contrib non-free" >> sources.list && \
    echo "# deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main contrib non-free" >> sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main contrib non-free" >> sources.list && \
    echo "# deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main contrib non-free" >> sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main contrib non-free" >> sources.list && \
    echo "# deb-src https://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main contrib non-free" >> sources.list && \
    apt-get update && \
    apt-get install libfreetype6-dev -y && \
    apt-get install libpng-dev -y && \
    apt-get install libjpeg62-turbo-dev -y && \
    apt-get install libicu-dev -y && \
    apt-get install libmcrypt-dev -y && \
    apt-get install libcurl4-openssl-dev -y && \
    apt-get install wget -y && \
    apt-get install curl -y && \
    apt-get install git -y  && \
    apt-get install zip -y  && \
    apt-get install libzip-dev -y && \
    apt-get install libssl-dev -y && \
    apt-get install libz-dev -y && \
    apt-get install libnghttp2-dev -y && \
    apt-get install libpcre3-dev -y && \
    apt-get clean -y && \
    apt-get autoremove -y && \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include --with-jpeg-dir=/usr/include && \
    docker-php-ext-install gd && \
    docker-php-ext-install pdo_mysql && \
    docker-php-ext-install mysqli && \
    docker-php-ext-install exif && \
    docker-php-ext-install zip && \
    docker-php-ext-install bcmath && \
    docker-php-ext-install sockets

# Composer
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && composer self-update --clean-backups \
    && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer
    
# Redis extension
RUN wget https://pecl.php.net/get/redis-${PHPREDIS_VERSION}.tgz -O /tmp/redis.tar.tgz \
    && pecl install /tmp/redis.tar.tgz \
    && rm -rf /tmp/redis.tar.tgz \
    && docker-php-ext-enable redis

# xlswriter extension
RUN wget https://pecl.php.net/get/xlswriter-${XLSWRITER_VERSION}.tgz -O /tmp/xlswriter.tar.tgz \
     && pecl install /tmp/xlswriter.tar.tgz  \
     && rm -rf /tmp/xlswriter.tar.tgz \
     && docker-php-ext-enable xlswriter
     
# Swoole extension
RUN wget https://github.com/swoole/swoole-src/archive/v${SWOOLE_VERSION}.tar.gz -O swoole.tar.gz \
    && mkdir -p swoole \
    && tar -xf swoole.tar.gz -C swoole --strip-components=1 \
    && rm swoole.tar.gz \
    && ( \
    cd swoole \
    && phpize \
    && ./configure  --enable-openssl --enable-swoole-curl --enable-http2 \
    && make -j$(nproc) \
    && make install \
    ) \
    && rm -r swoole \
    && docker-php-ext-enable swoole
    
CMD docker-php-entrypoint php-fpm

EXPOSE 9000
```