FROM php:7.2-fpm

# Version
ENV PHPREDIS_VERSION 4.0.1 SWOOLE_VERSION 4.6.6 XLSWRITER_VERSION 1.3.7

# 设置时间
RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' > /etc/timezone

#更换源
RUN sed -i "s/deb.debian.org/mirrors.aliyun.com/g" /etc/apt/sources.list
RUN sed -i "s/http/https/g" /etc/apt/sources.list

# 更换
RUN apt-get update -y && \
    apt-get install libfreetype6-dev -y && \
    apt-get install libpng-dev -y && \
    apt-get install libjpeg62-turbo-dev -y && \
    apt-get install libicu-dev -y && \
    apt-get install libmcrypt-dev -y && \
    apt-get install libcurl4-openssl-dev -y && \
    apt-get install wget -y && \
    apt-get install curl -y && \
    apt-get install zip -y  && \
    apt-get install libzip-dev -y && \
    apt-get install libssl-dev -y && \
    apt-get install libz-dev -y && \
    apt-get install libnghttp2-dev -y && \
    apt-get install libpcre3-dev -y && \
    apt-get clean -y && \
    apt-get autoremove -y && \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include --with-jpeg-dir=/usr/include && \
    docker-php-ext-install gd && \
    docker-php-ext-install sockets bcmath pdo_mysql zip sockets pcntl exif mysqli

# Redis extension
RUN pecl install redis-${PHPREDIS_VERSION} && docker-php-ext-enable redis

# xlswriter extension
# RUN pecl install xlswriter-${XLSWRITER_VERSION} && docker-php-ext-enable xlswriter

#安装swoole
# RUN pecl install swoole-$SWOOLE_VERSION && docker-php-ext-enable swoole

RUN touch /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini &&  \
    echo "[opcache]" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini && \
    echo "zend_extension=opcache.so" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini && \
    echo "opcache.enable=1" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini && \
    echo "opcache.enable_cli=1" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini && \
    echo "opcache.memory_consumption=256" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini && \
    echo "opcache.interned_strings_buffer=8" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini && \
    echo "opcache.max_accelerated_files=100000" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini && \
    echo "opcache.max_wasted_percentage=5" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini && \
    echo "opcache.use_cwd=1" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini && \
    echo "opcache.validate_timestamps=1" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini && \
    echo "opcache.revalidate_freq=2" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini && \
    echo "opcache.save_comments=0" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini && \
    echo "# 其他php配置" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini && \
    echo "memory_limit=256M" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini && \
    echo "upload_max_filesize=50M" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini && \
    echo "post_max_size=50M" >> /usr/local/etc/php/conf.d/docker-php-ext-OPcache.ini

# Composer安装 与设置镜像地址
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && composer self-update --clean-backups \
    && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/

# 更改 fpm 的分组 因为我 宿主机有 www:x:1001:1001 分组跟用户 所以才做这样的处理 其他机器按照自己想要的分组去处理就好
# groupadd -g 1001 www
#RUN  useradd -u 1001 www && RUN sed -i "s/www-data/www/g" /usr/local/etc/php-fpm.d/www.conf

CMD docker-php-entrypoint php-fpm

EXPOSE 9000
